### ISSUE TITLE
Using `master` or `gh-pages` branch?

### ISSUE THREAD

**Issue by cvan** [aframevr/a-saturday-night#123]
@fernandojsg: I noticed for A-Blast, and it looks like too now for A Saturday Night, you're using `master` as the GH Pages branch. Is that supposed to be the case for ASN too? Because if so, need to change that from Settings and delete the `gh-pages` branch here.

**Comment by fernandojsg** [comment]
We should keep using `gh-pages` here, the problem was with `a-blast` so I need to create a `gh-pages` there too. 
We had it that way as In `a-blast` we didn't use to work in the same feature at the same time so every time we deployed something was in production, here we've been working more diego and me on some features and we used master sometimes as a preproduction before deploying to gh-pages. O:)
